/**
 * Designs as local files (E-279 #3051).
 *
 * A design's html, css and description can run to tens of thousands of
 * characters. When the agent works in a checkout, get_design writes them to
 * `.ezmodo/designs/<slug>/` instead of returning them, the same way
 * get_document writes `.ezmodo/docs/`. The agent reads what it needs and
 * changes the files with its own Edit tool, which is already a diff, and
 * `manage_design update fromFiles:true` pushes them back. The markup then never
 * passes through the model at all, in either direction.
 *
 * `design.json` beside the files records the design's id, the updatedAt it was
 * downloaded at (sent back as expectedUpdatedAt, so a push cannot overwrite a
 * newer edit) and a hash of each file as downloaded. The hashes are how this
 * tells "the agent edited this" from "this is what the server has", so a
 * re-download never silently discards unpushed work.
 *
 * With no `.ezmodo` directory (the remote connector, a container) nothing here
 * applies and callers fall back to returning content inline.
 */

import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';
import { findConfigPath } from './local-cache.js';

/** Which file holds which design field. */
export const DESIGN_FILES = Object.freeze({
  html: 'index.html',
  css: 'styles.css',
  description: 'notes.md',
});

const META_FILE = 'design.json';
const FIELDS = Object.keys(DESIGN_FILES);

const hash = (text) => crypto.createHash('sha256').update(text ?? '', 'utf8').digest('hex');

/** `.ezmodo/designs`, or null when this is not a tracked checkout. */
export async function designsRoot() {
  const configPath = await findConfigPath();
  return configPath ? path.join(path.dirname(configPath), 'designs') : null;
}

async function readText(file) {
  try {
    return await fs.readFile(file, 'utf-8');
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
}

async function readMeta(dir) {
  const text = await readText(path.join(dir, META_FILE));
  if (text == null) return null;
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

/** The directory already holding this design, if it was downloaded before. */
async function findDir(root, designId) {
  let entries;
  try {
    entries = await fs.readdir(root, { withFileTypes: true });
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const dir = path.join(root, entry.name);
    const meta = await readMeta(dir);
    if (meta?.id === designId) return dir;
  }
  return null;
}

/** A fresh directory name: the slug, or slug + id prefix if that is taken. */
async function newDir(root, design) {
  const base = String(design.slug || design.id).replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/^[-.]+/, '') ||
    design.id;
  const first = path.join(root, base);
  if ((await readMeta(first)) == null) return first;
  return path.join(root, `${base}-${String(design.id).slice(0, 8)}`);
}

function filesIn(dir) {
  return Object.fromEntries(FIELDS.map((f) => [f, path.join(dir, DESIGN_FILES[f])]));
}

/** Fields whose file differs from what was downloaded. A missing file is not a change. */
async function changedFields(dir, meta) {
  const changed = [];
  for (const field of FIELDS) {
    const text = await readText(path.join(dir, DESIGN_FILES[field]));
    if (text != null && hash(text) !== meta?.hashes?.[field]) changed.push(field);
  }
  return changed;
}

async function writeAll(dir, design) {
  await fs.mkdir(dir, { recursive: true });
  const hashes = {};
  for (const field of FIELDS) {
    const text = design[field] ?? '';
    await fs.writeFile(path.join(dir, DESIGN_FILES[field]), text, 'utf-8');
    hashes[field] = hash(text);
  }
  const meta = {
    id: design.id,
    organizationId: design.organizationId,
    projectId: design.projectId ?? null,
    kind: design.kind,
    name: design.name,
    status: design.status,
    updatedAt: design.updatedAt,
    hashes,
    note: 'Written by the EzModo MCP server. Edit the other files, then push them with ' +
      'manage_design action:"update" designId fromFiles:true. Do not edit this file.',
  };
  await fs.writeFile(path.join(dir, META_FILE), JSON.stringify(meta, null, 2) + '\n', 'utf-8');
}

/**
 * Write a design's fields to its directory.
 *
 * Returns null when there is no `.ezmodo` directory. When the files hold edits
 * that were never pushed, nothing is written unless `overwriteLocal` is set,
 * and `localChanges` names the edited fields.
 */
export async function writeDesignFiles(design, { overwriteLocal = false } = {}) {
  const root = await designsRoot();
  if (!root) return null;
  const existing = await findDir(root, design.id);
  const dir = existing ?? (await newDir(root, design));
  if (existing && !overwriteLocal) {
    const changed = await changedFields(existing, await readMeta(existing));
    if (changed.length > 0) return { dir, files: filesIn(dir), localChanges: changed };
  }
  await writeAll(dir, design);
  return { dir, files: filesIn(dir) };
}

/**
 * Read a downloaded design back: its metadata, the text of each field, and
 * which fields were edited since download.
 */
export async function readDesignFiles(designId) {
  const root = await designsRoot();
  if (!root) {
    throw new Error(
      'fromFiles needs a local .ezmodo directory, and there is none here. Send edits or the ' +
        'fields themselves instead.'
    );
  }
  const dir = await findDir(root, designId);
  if (!dir) {
    throw new Error(
      `Design ${designId} has not been downloaded here. Call get_design designId:"${designId}" ` +
        'first, edit the files it writes, then push them.'
    );
  }
  const meta = await readMeta(dir);
  const fields = {};
  for (const field of FIELDS) {
    fields[field] = await readText(path.join(dir, DESIGN_FILES[field]));
  }
  return { dir, meta, fields, changed: await changedFields(dir, meta), files: filesIn(dir) };
}

/** After a successful push: the files ARE the server's version now. */
export async function recordPushed(dir, meta, fields, updatedAt) {
  const hashes = { ...meta.hashes };
  for (const field of FIELDS) {
    if (fields[field] != null) hashes[field] = hash(fields[field]);
  }
  const next = { ...meta, updatedAt, hashes };
  await fs.writeFile(path.join(dir, META_FILE), JSON.stringify(next, null, 2) + '\n', 'utf-8');
}

/**
 * A push lost the race: keep the agent's version beside the files as
 * `*.mine`, and put the server's latest in the files themselves, so the agent
 * reapplies its change to the current version rather than overwriting it.
 */
export async function setAsideAndRefresh(dir, latest) {
  const mine = {};
  for (const field of FIELDS) {
    const file = path.join(dir, DESIGN_FILES[field]);
    const text = await readText(file);
    if (text == null) continue;
    const ext = path.extname(DESIGN_FILES[field]);
    const aside = path.join(dir, `${path.basename(DESIGN_FILES[field], ext)}.mine${ext}`);
    await fs.writeFile(aside, text, 'utf-8');
    mine[field] = aside;
  }
  await writeAll(dir, latest);
  return mine;
}
